name: CI

on:
  pull_request:
  push:
    branches: ['master']
    tags: ['v*']

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.*'
    - run: dotnet test
      if: matrix.os == 'ubuntu-latest'
    - run: dotnet test --filter 'Category!=integration'
      if: matrix.os == 'windows-latest'
